---
- name: Grant additional privileges to a user
  hosts: all
  become: true
  tasks:
    - name: Add user to additional groups
      user:
        name: "{{ lookup('env', 'username')}}"
        groups: "{{ lookup('env', 'groups')}}"
        append: yes
