---
- hosts: sbc
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Run UniFi Controller Docker container
      shell: docker run -d --name unifi-controller --network host -v /UniFi/data:/unifi -v /UniFi/log:/var/log/unifi -e TZ=Europe/Stockholm ryansch/unifi-rpi:latest

