---
- hosts: sbc
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Stop and remove existing UniFi Controller container
      command: docker rm -f unifi-controller
      ignore_errors: true
