---
- hosts: sbc
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Stop UniFi Controller Docker container
      shell: docker stop unifi
      ignore_errors: true
